### ISSUE TITLE
(Sugerencia) Separacion logo - links

### ISSUE THREAD

**Issue by Josemiranda989** [FranBudde/mercadoLiebreFrancisco#4]
- El logo y los links podrìan quedar mejor con una separaciòn de space between o con alguna separaciòn
![image](https://github.com/FranBudde/mercadoLiebreFrancisco/assets/84145112/a6415c04-a3bd-4d84-bf49-d9c3e4dadbc0)

**Comment by FranBudde** [comment]
no quiero
